### ISSUE TITLE
Wheres the loadstring?

### ISSUE THREAD

**Issue by AverageCrystalMayBeAFurry** [debug420/Ez-Hub#33]

**Comment by debug420** [comment]
What do you mean where is the loadstring? Could you elaborate?

**Comment by AverageCrystalMayBeAFurry** [comment]
I can't find a loadstring for ezhub, does it have one

**Comment by debug420** [comment]
loadstring(game:HttpGet(('https://raw.githubusercontent.com/debug420/Ez-Industries-Launcher-Data/master/Launcher.lua'),true))()
